apiVersion v1
kind Service
metadata
  labels
    service hrhyv2-react
  name hrhyv2-react-svc
spec
  ports
  - name 3000
    port 80
    targetPort 3000
  type LoadBalancer
  selector
    service hrhyv2-react