apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: 812675885124.dkr.ecr.ap-northeast-1.amazonaws.com/myrepo
  newTag: fe_0.0.9
secretGenerator:
- behavior: merge
  envs:
  - conf/app.env
  name: hrhyv2-react-secret
