apiVersion kustomize.config.k8s.iov1beta1
kind Kustomization
resources
- ....base
images
- name 685766701737.dkr.ecr.ap-northeast-1.amazonaws.comtest
  newTag fe_1-1
secretGenerator
- behavior merge
  envs
  - confapp.env
  name hrhyv2-react-secret