apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: 685766701737.dkr.ecr.ap-northeast-1.amazonaws.com/test
  newTag: fe_0.0.8
secretGenerator:
- behavior: merge
  envs:
  - conf/app.env
  name: hrhyv2-react-secret
